#!/bin/bash

# install mktorrent
# check result on e.g. http://torrenteditor.com/

if [ "${1}" = "" -o "${2}" = "" ]; then
	echo "Usage: ${0} <version> <iso file>"
	echo -e "\tversion:\te.g. 2012.10.06 or archboot/2012.10.06"
	echo -e "\tiso file:\te.g. ./archlinux-2012.10.06-core-x86_64.iso"
	exit 1
fi

archver="${1}"
isofile="${2}"

echo 'Creating webseeds...'
httpmirrorlist=$(curl https://www.archlinux.org/mirrorlist/all/http/ \
	| grep '#Server = http' \
	| awk "{print \$3\"/iso/${archver}/\";}" \
	| sed -e 's#/$repo/os/$arch##' \
	      -e 's#\s*# -w #')

echo 'Building torrent...'
mktorrent \
	-l 19 \
	-c "Arch Linux ${archver} (www.archlinux.org)" \
	${httpmirrorlist} \
	"${isofile}"
